apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: debezium-cluster-kafka-bootstrap:9092
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1
  jvmOptions:
    -Xms: 512m
    -Xmx: 1g
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  groupId: connect-cluster
  configStorageTopic: connect-cluster-configs
  offsetStorageTopic: connect-cluster-offsets
  statusStorageTopic: connect-cluster-status
  build:
    output:
      type: docker
      #Replace with the registry to push image. If running with minikube with registry addon, get IP by running:
      #kubectl -n kube-system get svc registry -o jsonpath='{.spec.clusterIP}'
      image: 10.101.37.168/debezium-connect-postgres:latest
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.3.1.Final/debezium-connector-postgres-3.3.1.Final-plugin.tar.gz