apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  namespace: default
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["pods", "pods/exec", "pods/log", "jobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow
  namespace: default
roleRef:
  kind: Role
  name: airflow
  apiGroup: rbac.authorization.k8s.io
